#!/bin/bash

filename=$1

if [ ! -f ./luatool.py ]
then
    # Fetch luatool from https://github.com/4refr0nt/luatool if we don't yet have it    
    wget https://raw.githubusercontent.com/4refr0nt/luatool/master/luatool/luatool.py
fi



