#!/bin/bash

serial_config="--port /dev/ttyUSB0 --baud 9600"

./luatool.py $serial_config --wipe

./luatool.py $serial_config --src ${FIRMWARE_BASE}/nodemcu-firmware/lua_modules/ds18b20/ds18b20.lua  --dest ds18b20.lua --compile

files="config.lua send_temp.lua"

for filename in $files
do
    echo "** Uploading $filename"
    ./luatool.py $serial_config --src ./src/ds18b20/${filename} --dest ${filename} --compile
done

filename="init.lua"
./luatool.py $serial_config --src ./src/ds18b20/${filename} --dest ${filename} --restart
