#!/bin/bash

files="config.lua post_message.lua send_dht.lua init.lua"

for filename in $files
do
    echo "** Uploading $filename"
    ./luatool.py --port /dev/ttyUSB0 --src ./src/dht/${filename}  --dest ${filename} --baud 9600
done
